# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppHome_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.12.0'
  pod "ESTabBarController-swift"
  pod 'Material'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'pop', '~> 1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  # Pods for AppHome_1

end
